### ISSUE TITLE
Awesome plugin! But one request...

### ISSUE THREAD

**Issue by Hasjessew** [c103/chrome_parameters#46]
Could you add in automatic decode and re-encode for URL encoded entities (spaces, special characters, etc that are all encoded using a percent?)

**Comment by inuyasha82** [comment]
Thank you. :)
Yes, it seems a good idea. 
I think it will be included in version 1.4

**Comment by inuyasha82** [comment]
This feature is now implemented into my personal repository (check inuyasha82 chrome-parameters fork) and as i mentioned above will be available as soon as release 1.4 will be ready.
